### ISSUE TITLE
Update condition to hold successful condition

### ISSUE THREAD

**Issue by aceamarco** [argoproj-labs/appsource#23]
# Summary
Currently the appsource status subresource only holds error conditions. But in order to utilize kubectl's convenient mechanic that lets commands execute after a condition is met we should add successful conditions.

# Motivation
`kubectl` commands can wait for certain conditions to be met, users might want to wait until an application has been successfully been created to do something like describing it.

# Proposal
Add a new `AppSourceConditionType` called `ApplicationCreationSuccess` that is set after we successfully create an application. Also add a type called `ApplicationExistsOk` that is set when we reconcile the AppSource and it exists already.

**Comment by alexmt** [comment]
Thanks for creating the ticket. I would suggest following Kubernetes convention. Here is condition example:

success:

```yaml
status:
  conditions:
  - type: ApplicationCreationSuccess
    status: "True" 
    message: Application successfully created
```

failed:

```yaml
status:
  conditions:
  - type: ApplicationCreationSuccess
    status: "False" 
    reason: ApplicationCreationError
    message: Some error message
```
