### ISSUE TITLE
Notifications for Applications created by AppSource

### ISSUE THREAD

**Issue by aceamarco** [argoproj-labs/appsource#5]
# Summary
We can utilize the pre-existing Notifications Engine to add a notifications field to the AppSource instance — so that Dev Teams can be notified about what is happening with their applications.
# Motivation
Dev teams can stay informed about the state of their Applications through notifications.
# Proposal
We add a optional `notifications.channel` field to the AppSource instance that will add an annotation to the Application within the Application Create Request made by the controller.

Here is an example AppSource instance manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppSource
metadata:
  name: appsource-sample1
  namespace: my-project-us-west-2
spec:
  path: kustomize-guestbook
 # New Field
  notifications.channel: my_channel
  repoURL: https://github.com/argoproj/argocd-example-apps
```
This is the Application it would create:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    # New annotation
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my_channel
. . .
```
